baseURL = "https://nilla-moige.github.io/chrome-extension-linkedIn-job-snatcher/"
languageCode = "en-us"
title = "LinkedIn Job Snatcher"
theme = "ananke"
themeDir = "themes/ananke"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
      
# Meta
[params]
  author = "Team Moige"
  description = "Quickly snag LinkedIn job descriptions, append AI-friendly prompts, and supercharge your job search."
  keywords = ["LinkedIn","jobs","Chrome extension","AI","clipboard"]

[menu]
  [[menu.main]]
    name = "Features"
    url  = "/features/"
    weight = 10

  [[menu.main]]
    name = "How It Works"
    url  = "/how/"
    weight = 20

  [[menu.main]]
    name = "Install"
    url  = "/install/"
    weight = 30

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 40